version: "3.1"
services:
  web:
    build:
        context: docker
        dockerfile: Dockerfile
    container_name: algocoin
    command: ls -la /
    volumes:
      - .:/code
    ports:
      - "8080:8080"
