version: "3.1"
services:
  firebase:
    build:
        context: docker
        dockerfile: firebaseDockerfile
    container_name: algocoin
    command: ls -la /
    volumes:
      - ./firebase:/code
    ports:
      - "8080:8080"
